[[members]]
nickname = "ari"
link = "https://archerintro.straw.page/"

[[members]]
nickname = "arthesia"
link = "https://primevaltextureliker.straw.page/"

[[members]]
nickname = "linn"
link = "https://sugarp1lled.straw.page/"

[[members]]
nickname = "loomie"
link = "https://asceptical.straw.page/"

[[members]]
nickname = "prescientmoon"
link = "https://moonythm.dev"

[[members]]
nickname = "shirahimes-servant"
link = "https://shirahimes-servant.straw.page/"

[[members]]
nickname = "taya"
link = "https://tayalex.straw.page/"
